### PR TITLE
Rename Android lib

### PR DESCRIPTION
**Pull request by hannesa2**
Your Android library has the name `app`.
Sorry, this is misleading  and kind of wrong, now it looks better (in my point of view)

### Before
image

###  New
image

This pull request is based on #660 to have a CI build for it

### CODE REVIEW

**Comment by hannesa2** [comment]
But now I'm confused: You don't use it ? 
image

**Comment by tanersener** [comment]
> Or from where does this implementation 'com.arthenica:mobile-ffmpeg-full:4.4.LTS' comes from ?

It comes from `jcenter()`. 

Test application is used to test both the local build and the artifact published to `jcenter()`. We can not have both of these dependencies enabled at the same time. So, I'm enabling the dependency I want to test before the test.

**Comment by hannesa2** [comment]
It's an easy step, but produces a lot of changes.
You see what I suggest and I guess you trust yourself most, so I close this and you can do, it don't do it

**Comment by tanersener** [comment]
Actually, it was possible to merge this. The only problem was the changes coming from your other PR, the one about Github Actions. That's why it wasn't merged. 

If you create it again targeting the `development` branch, without Github Actions, it can be reviewed and merged.

**Pull request closed without merging**
