### PR TITLE
Android Studio 3.5.2

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by tanersener** [comment]
@hannesa2 Thanks for the pull request. But these changes are already applied in the development branch.

**Comment by hannesa2** [comment]
Yes, as I see `Android Studio 3.5.2` is pointless. But the Gradle noise is till there

**Comment by tanersener** [comment]
> Yes, as I see `Android Studio 3.5.2` is pointless. But the Gradle noise is till there

Where, can you show me?

**Comment by hannesa2** [comment]
This is the noise

image

**Comment by tanersener** [comment]
Do you want me to commit `build`, `.idea` and `local.properties`? Can you explain what's wrong here?

**Comment by hannesa2** [comment]
The leading `/ `is pointless. 
Eg, now all found `build `are ignored. Not only the topmost

**Comment by tanersener** [comment]
Yes, `.gitignore` file can be optimised. Thanks for pointing that out. But I can't accept this pull request just to optimize `.gitignore` files. `development` branch already uses `gradle` plugin `3.5.3` and gradle version `6.0.1`. Is there anything else you want me to use from this pull request?

**Comment by hannesa2** [comment]
The double usage of Gradle is also an issue.
Performing this commands will add my findings to your branch 
```
git checkout development
git remote add hannesa2 https://github.com/hannesa2/mobile-ffmpeg.git
git fetch hannesa2
git cherry-pick a1112502a00e702c0
git remote remove hannesa2
```

**Comment by tanersener** [comment]
Thanks, merged your [commit](https://github.com/tanersener/mobile-ffmpeg/commit/d8b1754272cb3bc84affad7acba5ce7ee0c45fce) into development.

**Comment by tanersener** [comment]
and now they're merged to master.

**Pull request closed without merging**
