### PR TITLE
- Migration of Objective-C code to Swift 5.0

### PR DESCRIPTION
**Pull request by jvega1976**
Hello,
 Not sure  if you could be interested, but I have migrated the iOS Objective-C code to Swift, so I'm contributing it in case you would like to use it for future releases. 

Below is a short description of the multiple changes.  I tried to not change the actual code, so I mostly copied (_and sometimes renamed)_ the actual files (_like the "ios-*.sh" scripts, that I copied and renamed as "apple-*.sh"_); or the fftools C Language files that I copied to **iOS/Sources/fftools** (_I did small changes in those files to enable full concurrent execution in Swift)_.  New Swift files are located at **ios/Sources/MobileFFmpeg.** And  the Xcode project is inside the **ios** folder.

In general these are the updates:

- Migration of Objective-C code to Swift 5.0.
- Addition of "apple.sh" shell script to generate a "Binary Framework"
  for iOS, iOS Simulator, Mac Catalyst and Mac OS plaforms.
- Adoption of Cocoa design patters for Framework compatibility with Objective-C Applications/Frameworks.
- Addition of "apple-*.sh" scripts to support generation of external libraries.
  for Apple Intel (x86_64) and Apple Silicon (arm64) architectures. Scripts supports
  generation for platforms: macOS (Intel and Apple Silicon), Catalyst (Intel and Apple Silicon),
  iOS Simulator(Intel and Apple Silicon) and iOS (arm64).
- Addition of Xcode project (MobileFFmpeg.xcodeproj) to support generation of
  Framework.  New "apple.sh" script make use of this project to generate
  final individual Frameworks.  Project can be integrated in other Xcode
  projects, used for testing, or Frameworks generation for specific
  Platform/Architecture.
- Xcode project include Test Unit with examples of new APIs.
- Addition of Swift Package for distribution of final Binary Framework
  (XCFramework).

### CODE REVIEW

**Comment by tanersener** [comment]
Thanks, it looks like a big PR. There are a lot of changes introduced in these files.

Let me have a look at them. It will take time to understand how they work and whether we can merge them or not.

**Comment by NCrusher74** [comment]
Speaking as person working in Swift, I'm very excited about this! My current project isn't using FFMpeg because I put the one that does on the back burner in the hopes of this very thing eventually coming to be. Thank you!

**Comment by jvega1976** [comment]
Your welcome,

I’m sorry if my explanation about the changes was to detailed, is just that in past experiences they asked me to explain as much I could, so they could understand the proposed changes.

**Comment by tanersener** [comment]
I see some issues that make it difficult to merge this PR.

- `apple.sh` script does a lot of things but doesn't cover tvOS
-  Updated build scripts and Swift API doesn't support LTS releases: `@available(iOS 13.0, macOS 10.15, *)`
- I want to keep Android and Apple APIs identical as much as possible. But Swift API introduced in this PR is very different than the Android API. They look like two separate APIs
- `module.modulemap` used by `apple.sh` script includes headers for all libraries. If one of the libraries is not enabled, then the build fails with `header not found` errors. You don't have any other option than enabling all external libraries
- Disabling architectures is not handled well by `apple.sh` script. If, at least one of the architectures is disabled, `apple.sh` fails to create an XCF framework

**Comment by Alanko5** [comment]
@jvega1976  Will you make a script to support tvOS as well?

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).

**Pull request closed without merging**
