### PR TITLE
Add option to build LADSPA audio plugin support.

### PR DESCRIPTION
**Pull request by tonygentilcore**
The --enable-ladspa option is disabled by default and not included
in the official builds.

The src/ladspa/ directory is copied from
http://www.ladspa.org/download/ladspa_sdk_1.15.tgz with modifications
to the Makefile to support cross compilation.

### CODE REVIEW

**Comment by tanersener** [comment]
Thanks for the pull request. I don't know much about `LADSPA`. Could you please give some detail about it? What is it used for, why mobile devices need it, a command example if possible?

**Comment by tonygentilcore** [comment]
LADSPA is the Linux Audio Developer's Simple Plugin API (https://www.ladspa.org/). There are hundreds of open source audio effects plugins written for it to do things like pitch shifting, rate shifting, equalizing, reverb, etc. I'm planning to use it for an app that can apply various audio effects like that.

To use it, one must build the desired plugin as an `.so` and include it in the project's `Resources`. This patch builds the SDK's example plugins such as `delay.so`, but doesn't build any real third party plugins. Then they're invoked similarly to ffmpeg's builtin audio filters using the `-af` switch, e.g.
`ffmpeg -y -i ${INFILE} -af ladspa={SOFILE}:delay_5s ${OUTFILE}`

Not sure whether this feature is generally applicable enough to be included in this library or not. No worries either way, just thought that since I'd put this together, I'd share.

**Comment by tanersener** [comment]
Thanks for providing detailed information. It looks like a useful library. However using the library is not very straightforward when compared to other supported libraries. I haven't included `frei0r` support because of a similar complexity. I prefer not to merge it if it is OK for you.

**Comment by tonygentilcore** [comment]
No problem. Thanks again for the library.

**Pull request closed without merging**
