### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/mobile-ffmpeg ❤️

  What it does:
  - adds a badge to show the latest number of financial contributors
  - adds a banner displaying contributors to the project on GitHub
  - adds a banner displaying all individuals contributing financially on Open Collective
  - adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website

P.S: As with any pull request, feel free to comment or suggest changes.

  Thank you for your great contribution to the Open Source community. You are awesome! 🙌
  And welcome to the Open Collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other Open Source sustainers!

### CODE REVIEW

**Comment by tanersener** [comment]
Can we increase the level of headers and add numbers to them?

```
### 8. Contributors
#### 8.1 Code Contributors
#### 8.2 Financial Contributors
#### 8.2.1 Individuals
#### 8.2.2 Organizations
```
### 8. Contributors
#### 8.1 Code Contributors
#### 8.2 Financial Contributors
#### 8.2.1 Individuals
#### 8.2.2 Organizations

**Comment by tanersener** [comment]
@monkeywithacupcake any comments about my suggestions?

**Comment by monkeywithacupcake** [comment]
Done. Apologies. I had edits open and assumed you had made those changes!

**Comment by tanersener** [comment]
@monkeywithacupcake thanks 👍

**Comment by tanersener** [comment]
Pull request is merged. Do you have any recommendations to improve the avatars in `7.2.2 Organizations`? It would be great if we can remove those blank avatars.

**Pull request merged**
