### PR TITLE
Github action for CI

### PR DESCRIPTION
**Pull request by hannesa2**
I see you don't have a CI for this repo.
Here is at least a pull request check for Android.

### CODE REVIEW

**Comment by hannesa2** [comment]
This is a pre-task for other Android improvements

**Comment by tanersener** [comment]
This project uses Travis CI. There is a [.travis.yml](https://github.com/tanersener/mobile-ffmpeg/blob/master/.travis.yml) file in the project root directory. It covers both build types of Android, iOS and tvOS.

Any reason to switch to another CI?

**Comment by hannesa2** [comment]
Yes, because Travis is not running see eg https://github.com/tanersener/mobile-ffmpeg/pull/654.
Github actions are much faster and with it you can run Espresso out of the box

**Comment by tanersener** [comment]
> Yes, because Travis is not running see eg #654.

How could this be a reason to switch to another CI? We don't see anything running for PRs because only `master` and `development` branches are enabled in `.travis.yml` file.

> Github actions are much faster 

Based on what? Jobs defined in this CI workflow only runs a single gradle command. Contrarily, jobs inside `.travis.yaml` file runs the actual build scripts (`android.sh`, `ios.sh`, `tvos.sh`). Don't we need to have the same CI build steps defined for Github Actions as well before coming to the conclusion that one of them is faster than the other?

If I see that Github Actions is capable of running the same build jobs faster than Travis, I'll be happy to review and merge that PR. But in this PR I don't see these. I can't approve this.

**Comment by hannesa2** [comment]
I see the spirit here. Let's stuck on Travis

**Pull request closed without merging**
